name: Nutriboard Service app
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: cypress/included:9.4.1

    # Service containers to run with `container-job`
    services:
      cypress-docker:
        image: node:10.18-jessie
      # Label used to access the service container
      nutriboard-postgresql:
        # Docker Hub image
        image: postgres:14.5
        # Provide the password for postgres
        env:
          POSTGRES_USER: nutriboard
          POSTGRES_PASSWORD:
          POSTGRES_HOST_AUTH_METHOD:  trust
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      nutriboard-app:
        image: tontonlaforce/nutriboarddd
        env:
          _JAVA_OPTIONS: -Xmx512m -Xms256m
          SPRING_PROFILES_ACTIVE: prod,api-docs
          MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: true
          SPRING_DATASOURCE_URL: jdbc:postgresql://nutriboard-postgresql:5432/nutriboard
          SPRING_LIQUIBASE_URL: jdbc:postgresql://nutriboard-postgresql:5432/nutriboard
          JHIPSTER_SLEEP: 30 # gives time for other services to boot before the application
        # If you want to expose these ports outside your dev PC,
        ports:
          - 8080:8080

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: |
          ls
          echo ----------------------------------------
          npm install --unsafe-perm
          npx cypress --version
#          apt-get update
#      - name: Public IP
#        id: ip
#        uses: haythem/public-ip@v1.3
      - name: Request Nutriboard App
        run: |
          apt-get update
          apt-get install curl -y
          curl nutriboard-app:8080
      - name: Run Tests E2E
        env:
          CYPRESS_BASE_URL: nutriboard-app:8080/
        run: npx cypress run --env allure=true -b chrome
      - name: Generate Report
        run: npm run allure:report
