name: Nutriboard Service app
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: cypress/included:12.2.0
      options: --user root

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: |
          ls
          echo ----------------------------------------
          uname --all
          echo ----------------------------------------
          apt-get install sudo
          echo ----------------------------------------
          sudo npm --version
          echo ----------------------------------------
          sudo npx cypress --version
          echo ----------------------------------------
          #sudo npm ci
      - name: Init new repo in dist folder and commit generated files
        run: |
          sudo lsb_release -a
          sudo apt-get install shopt -y
          sudo shopt -s extglob
          apt-get update
