name: Deploy to GitHub pages
on:
  push:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate static files
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      #      - run: npm ci
      # - run: npm run build
      #      - name: Run Tests E2E
      #        run: npm run cypress:run
      #      - name: Generate Report
      #        run: npm run allure:report
      - name: Get if branch exist
        run: |
          TEST=$(git rev-parse --verify --quiet gh-page && echo true || echo false)
          echo "BRANCH_IS_EXISTING=${TEST}" >> $GITHUB_ENV
      - name: Delete branch gh-page if exists
        run: echo ----------------- ${env.BRANCH_IS_EXISTING} ------------------------
